name: stayfitconnected
description: "StayFitClub"
publish_to: 'none'
version: 1.1.3+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  http: ^1.2.2
  pretty_qr_code: ^3.3.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" 

flutter:
  uses-material-design: true


  assets:
    - assets/
